Repository DeveloperAcademy-POSTECH/MC3-Team12-PeepPeep, pull requests merged in 2023-07, with the labels that each got.

#13 [Add/#8] InitialSetupView
  InitialSetupView.swift
  PeepPeep/InitialSetupScreen/InitialSetupView.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
Labels: ✨ Feat

#16 [Add/#12] WidgetView 추가
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/Widget/WidgetView.swift
Labels: ✨ Feat

#15 [Add/#10] Add-SplashView
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/SplashView.swift
  PeepPeep/SplashScreen/SplashView.swift
Labels: ✨ Feat

#14 [Add/#11] DailyFeedBackView, FinalReportView, WeeklyFeedBackView 파일 추가
  PeepPeep/DailyFeedBack/DailyFeedBackView.swift
  PeepPeep/FinalReport/FinalReportView.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/WeeklyFeedBack/WeeklyFeedBackView.swift
Labels: ✨ Feat

#19 [Chore] Project Initial Setup
  .gitignore
  PeepPeep/.DS_Store
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/Common/Components/EmptyComponents.swift
  PeepPeep/PeepPeep/Common/Extensions/EmptyExtensions.swift
  PeepPeep/PeepPeep/Common/Utils/EmptyUtils.swift
  PeepPeep/PeepPeep/Model/EmptyModel.swift
  PeepPeep/PeepPeep/View/CostumeBook/CostumesBookView.swift
  PeepPeep/PeepPeep/View/DailyFeedBack/DailyFeedBackView.swift
  PeepPeep/PeepPeep/View/FinalReport/FinalReportView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/InitialSetupView.swift
  PeepPeep/PeepPeep/View/MainScreen/MainView.swift
  PeepPeep/PeepPeep/View/SplashScreen/SplashView.swift
  PeepPeep/PeepPeep/View/WeeklyFeedBack/WeeklyFeedBackView.swift
  PeepPeep/PeepPeep/View/Widget/WidgetVIew.swift
  PeepPeep/PeepPeep/ViewModel/EmptyViewModel.swift
Labels: ✨ Feat

#28 [Feat/#28] Implement Screen Time
  PeepPeep/FeedBack/FeedBack.entitlements
  PeepPeep/FeedBack/FeedBack.swift
  PeepPeep/FeedBack/Info.plist
  PeepPeep/FeedBack/TotalActivityReport.swift
  PeepPeep/FeedBack/TotalActivityView.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/ContentView.swift
  PeepPeep/PeepPeep/PeepPeep.entitlements
  PeepPeep/PeepPeep/View/InitialSetupScreen/ActivitySummaryView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/InitialSetupView.swift
Labels: ✨ Feat

#39 [Fix/#38] Revert Conflict Issue with #27
  PeepPeep/Assets.xcassets/Paper.imageset/Contents.json
  PeepPeep/Assets.xcassets/Paper.imageset/Paper.png
  PeepPeep/Assets.xcassets/chick.imageset/Contents.json
  PeepPeep/Assets.xcassets/chick.imageset/chick.png
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/DailyFeedBack/DailyFeedBackView.swift
Labels: 🛠️ Fix

#45 [Feat/#42] MainView 그리기 완료 및 DeviceActivityView를 Main에 띄우기
  PeepPeep/DeviceActivityReportExtension/DeviceActivityExtension.swift
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/ChickStatusView.swift
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainActivityView.swift
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainView.swift
  PeepPeep/DeviceActivityReportExtension/ViewModel/MainActivityReport.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/InitialSetupScreen/InitialSetupView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/TimeSettingView.swift
  PeepPeep/PeepPeep/View/MainScreen/HelperView.swift
  PeepPeep/PeepPeep/View/MainScreen/MainView.swift
Labels: ✨ Feat

#48 [Feat/#46] SettingView 구현
  PeepPeep/Assets.xcassets/GrayColor.colorset/Contents.json
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/Setting/SettingView.swift
Labels: ✨ Feat

#50 [Feat/#49] LoadingView 구현
  PeepPeep/Assets.xcassets/Color/GrayColor.colorset/Contents.json
  PeepPeep/Assets.xcassets/Logo_Typo.imageset/Contents.json
  PeepPeep/Assets.xcassets/Logo_Typo.imageset/Logo_Typo.png
  PeepPeep/Assets.xcassets/appstore.imageset/Contents.json
  PeepPeep/Assets.xcassets/appstore.imageset/appstore.png
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/ContentView.swift
  PeepPeep/PeepPeep/View/SplashScreen/LoadingView.swift
  PeepPeep/PeepPeep/View/SplashScreen/SplashView.swift
Labels: ✨ Feat

#57 Fix/#56 change UI initial setup
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/TotalActivityView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ActivitySummaryView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ProgressBar.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ScreenTimeRequestView.swift
  PeepPeep/PeepPeep/View/SplashScreen/SplashView.swift
Labels: 🛠️ Fix

#68 [Fix/#58] Device Report based on App Selection
  PeepPeep/DeviceActivityReportExtension/DeviceActivityExtension.swift
  PeepPeep/DeviceActivityReportExtension/Model/ActivityReportModels.swift
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/TotalActivityView.swift
  PeepPeep/DeviceActivityReportExtension/ViewModel/MainActivityReport.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/Model/Chick.swift
  PeepPeep/PeepPeep/Model/ScreenTimeAppSelection.swift
  PeepPeep/PeepPeep/PeepPeepApp.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ActivitySummaryView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ChickNamingView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ProgressBar.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ScreenTimeRequestView.swift
  PeepPeep/PeepPeep/ViewModel/ChickNamingVIewModel.swift
  PeepPeep/PeepPeep/ViewModel/ScreenTimeAppSelectionViewModel.swift
  PeepPeep/PeepPeepCommons/Extensions/TimeInterval+.swift
  PeepPeep/PeepPeepCommons/Themes/Colors.swift
  PeepPeep/PeepPeepCommons/Utils/TimeIntervalFormatter.swift
Labels: ✨ Feat, 🛠️ Fix

#70 Fix/#69 Resolve Conflict Issue with #68
  PeepPeep/DeviceActivityReportExtension/DeviceActivityExtension.swift
  PeepPeep/DeviceActivityReportExtension/View/DailyFeedBack/DiaryActivityView.swift
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainActivityView.swift
  PeepPeep/DeviceActivityReportExtension/ViewModel/MainActivityReport.swift
  PeepPeep/PeepPeep/View/DailyFeedBack/DailyFeedBackView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/TimeSettingView.swift
Labels: 🛠️ Fix

#73 [Fix/#69] Resolve Conflict Issue
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainActivityView.swift
  PeepPeep/DeviceActivityReportExtension/ViewModel/MainActivityReport.swift
Labels: 🐛 bug, 🛠️ Fix

#74 Fix/#69 resolve conflict issue with 68
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/InitialSetupScreen/ChickNamingView.swift
Labels: 🛠️ Fix

#78 [Feat/#44] CostumeBookView 구현
  PeepPeep/Assets.xcassets/Apple.imageset/Apple.png
  PeepPeep/Assets.xcassets/Apple.imageset/Contents.json
  PeepPeep/Assets.xcassets/Bag.imageset/Bag.png
  PeepPeep/Assets.xcassets/Bag.imageset/Contents.json
  PeepPeep/Assets.xcassets/Cake.imageset/Cake.png
  PeepPeep/Assets.xcassets/Cake.imageset/Contents.json
  PeepPeep/Assets.xcassets/Clover.imageset/Clover.png
  PeepPeep/Assets.xcassets/Clover.imageset/Contents.json
  PeepPeep/Assets.xcassets/Moon.imageset/Contents.json
  PeepPeep/Assets.xcassets/Moon.imageset/Moon.png
  PeepPeep/Assets.xcassets/Music.imageset/Contents.json
  PeepPeep/Assets.xcassets/Music.imageset/Music.png
  PeepPeep/Assets.xcassets/Newbie.imageset/Contents.json
  PeepPeep/Assets.xcassets/Newbie.imageset/Newbie.png
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/CostumeBook/CostumeBookView.swift
  PeepPeep/PeepPeep/View/CostumeBook/CostumesBookView.swift
Labels: ✨ Feat

#82 [Feat/#77] MainView와 MainActivityView 수정
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainActivityView.swift
  PeepPeep/PeepPeep/View/MainScreen/MainView.swift
Labels: ✨ Feat

#86 [Feat/#76] EmptyActivityView 구현
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/EmptyActivityView.swift
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/TotalActivityView.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/CostumeBook/CostumeBookView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ActivitySummaryView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ChickNamingView.swift
  PeepPeep/PeepPeep/View/MainScreen/MainView.swift
Labels: ✨ Feat

#88 [Fix/#85] SplashView 디자인 반영 완료
  PeepPeep/PeepPeep/View/SplashScreen/SplashView.swift
Labels: 🛠️ Fix

#92 [Feat/#90] HelperView 디자인 반영
  PeepPeep/Assets.xcassets/Emotion/GoOut.imageset/GoOut.png
  PeepPeep/Assets.xcassets/EmotionBar/GoOutBar.imageset/Contents.json
  PeepPeep/Assets.xcassets/EmotionBar/GoOutBar.imageset/GoOutBar.png
  PeepPeep/DeviceActivityReportExtension/View/MainScreen/MainActivityView.swift
  PeepPeep/DeviceActivityReportExtension/View/StressGauge/StressGaugeView.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/MainScreen/HelperView.swift
  PeepPeep/PeepPeep/View/MainScreen/MainView.swift
Labels: ✨ Feat

#100 Feat/#83 adjust initial setup screens
  PeepPeep/Assets.xcassets/Chick.imageset/Chick.svg
  PeepPeep/Assets.xcassets/Chick.imageset/Contents.json
  PeepPeep/Assets.xcassets/Icon/Hourglass.imageset/Contents.json
  PeepPeep/Assets.xcassets/Icon/Hourglass.imageset/Hourglass.png
  PeepPeep/Assets.xcassets/Icon/Hourglass.imageset/Hourglass.svg
  PeepPeep/Assets.xcassets/chick.imageset/chick.png
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/PieChartView.swift
  PeepPeep/DeviceActivityReportExtension/View/InitialSetupScreen/TotalActivityView.swift
  PeepPeep/DeviceActivityReportExtension/ViewModel/TotalActivityViewModel.swift
  PeepPeep/PeepPeep.xcodeproj/project.pbxproj
  PeepPeep/PeepPeep/View/InitialSetupScreen/ActivitySummaryView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ChickNamingView.swift
  PeepPeep/PeepPeep/View/InitialSetupScreen/ScreenTimeRequestView.swift
  PeepPeep/PeepPeepCommons/Themes/Colors.swift
  PeepPeep/PeepPeepCommons/Themes/Styles.swift
  PeepPeep/PeepPeepCommons/Utils/KeyboardResponder.swift
Labels: ✨ Feat, 🛠️ Fix

#102 [Feat/#93] SettingView 디자인 반영
  PeepPeep/PeepPeep/View/Setting/SettingView.swift
Labels: ✨ Feat

#107 [Feat/#105] SettingView 키보드 키고 끄기 및 한국어 자판으로 세팅
  PeepPeep/PeepPeep/View/Setting/SettingView.swift
Labels: ✨ Feat
